name: Build and Run Docker Compose

on:
  push:
    branches:
      - main  # Modifier si votre branche principale a un nom différent

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install Docker
      run: sudo apt-get update && sudo apt-get install -y docker.io docker-compose

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Set up environment variables
      uses: actions/setup-node@v2
      with:
        node-version: '20.11.1' 

    - name: Install npm dependencies
      run: npm install

    - name: Run Docker Compose
      run: docker-compose --env-file .env -f docker-compose.yml -p livecampus-environnement-tests up --force-recreate -d
