version: "3.8"
name: livecampus-environnement-tests
services:
  web-app:
    container_name: livecampus-next-js
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./:/app
    env_file:
      - .env
    ports:
      - '${WEB_EXPOSE_PORT}:${WEB_PORT}'
    networks:
      - cloud
    depends_on:
      - livecampus-mongo-db
    expose:
      - '${WEB_EXPOSE_PORT}'
  livecampus-mongo-db:
    container_name: livecampus-mongo-db
    image: mongo:7.0.7-jammy
    volumes:
      - ./.data:/data/db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: '${MONGO_ROOT_USERNAME}'
      MONGO_INITDB_ROOT_PASSWORD: '${MONGO_ROOT_PASSWORD}'
    networks:
      - cloud
networks:
  cloud:
    name: livecampus-cloud
    external: false
