version: "3.8"
name: livecampus-environnement-tests
services:
  web-app:
    container_name: livecampus-next-js
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    env_file:
      - .env
    ports:
      - '${WEB_EXPOSE_PORT}:${WEB_PORT}'
    expose:
      - '${WEB_EXPOSE_PORT}'
