name: Build and Run Docker Compose

on:
  push:
    branches:
      - main  # Modifier si votre branche principale a un nom différent

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    # Vérifier si Node.js est déjà installé
    - name: Check if Node.js is installed
      run: node --version
      continue-on-error: true
      id: check_node

    # Vérifier si Docker est déjà installé
    - name: Check if Docker is installed
      run: docker --version
      continue-on-error: true
      id: check_docker

    - name: Install npm dependencies
      run: npm install

    - name: Run Docker Compose
      run: |
        docker-compose --env-file .env -f docker-compose.yml -p livecampus-environnement-tests up --force-recreate -d
