name: Build and Run Docker Compose

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install npm dependencies
      run: npm install

    - name: Run Docker Compose
      run: |
        docker-compose --env-file .env -f docker-compose.yml -p livecampus-environnement-tests up --force-recreate -d
